name: Flask Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.1'  

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pip install -e .

      # Step 4: Set environment variables from GitHub Secrets
      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> $GITHUB_ENV
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> $GITHUB_ENV
          echo "MONGO_CLUSTER=${{ secrets.MONGO_CLUSTER }}" >> $GITHUB_ENV
          echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> $GITHUB_ENV
        #   echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV
      
      # Step 5: For modul 
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)"

      # Step 6: Run tests with coverage
      - name: Run tests with coverage
        run: |
          pytest -s

      # Step 7: Upload coverage results (if using codecov)
      - name: Upload coverage results
        uses: codecov/codecov-action@v2
